* added missing files to debian package * tried to add the race option to the network menu (work in progress commit) * tweaked cancel button position

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -10,24 +10,27 @@ set -e
 
 case "$1" in
   configure)
-      db_get shared/warguscdpath || true
-      CDPATH=${RET}
-      EXTRACTVIDEO=
-      EXTRACTMUSIC=
-      if [ -d "${CDPATH}" ]; then
-        db_get shared/wargusextractvideo || true
-        if [ ${RET} = "true" ]; then
-          EXTRACTVIDEO="-v"
+      db_get shared/wargusextractdata || true
+      if [ "$RET" = "true" ]; then
+        db_get shared/warguscdpath || true
+        CDPATH=${RET}
+        EXTRACTVIDEO=
+        EXTRACTMUSIC=
+        if [ -d "${CDPATH}" ]; then
+          db_get shared/wargusextractvideo || true
+          if [ ${RET} = "true" ]; then
+            EXTRACTVIDEO="-v"
+          fi
+          db_get shared/wargusextractmusic || true
+          if [ ${RET} = "true" ]; then
+            EXTRACTMUSIC="-v"
+          fi
+          echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/wargus"
+          /usr/share/games/stratagus/wargus/build.sh -p ${CDPATH} -m -b /usr/games -o /usr/share/games/stratagus/wargus -s -c ${EXTRACTVIDEO} ${EXTRACTMUSIC}
+        else
+          echo "${RET} doesn't exist - can't extract WarCraft II data" >&2
+          exit 1
         fi
-        db_get shared/wargusextractmusic || true
-        if [ ${RET} = "true" ]; then
-          EXTRACTMUSIC="-v"
-        fi
-        echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/wargus"
-        /usr/share/games/stratagus/wargus/build.sh -p ${CDPATH} -m -b /usr/games -o /usr/share/games/stratagus/wargus -s -c ${EXTRACTVIDEO} ${EXTRACTMUSIC}
-      else
-        echo "${RET} doesn't exist - can't extract WarCraft II data" >&2
-        exit 1
       fi
   ;;
   *)
