Rewrited debian/postinst for extracting data

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -5,52 +5,72 @@
 
 set -e
 
-# Maemo section
-if [ -f /etc/maemo_version ]; then
-	if [ "$1" != "configure" ]; then
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
-	fi
-	/usr/games/warextract || exit 1
-	exit 0
-fi
+extract() {
 
-# Source debconf library
-. /usr/share/debconf/confmodule
+	# Maemo section
+	if [ -f /etc/maemo_version ]; then
+		cd /opt/stratagus/share/wargus
+		/usr/games/warextract
+		return $?
+	fi
+
+	# Source debconf library
+	. /usr/share/debconf/confmodule
+	
+	db_get shared/wargusextractdata || true
+
+	if [ "$RET" = "true" ]; then
+
+		db_get shared/warguscdpath || true
+
+		CDPATH=${RET}
+		EXTRACTVIDEO=
+		EXTRACTMUSIC=
+
+		if [ -d "${CDPATH}" ]; then
+
+			db_get shared/wargusextractvideo || true
+			if [ ${RET} = "true" ]; then
+				EXTRACTVIDEO="-v"
+			fi
+
+			db_get shared/wargusextractmusic || true
+			if [ ${RET} = "true" ]; then
+				EXTRACTMUSIC="-m"
+			fi
+
+			db_stop || true
+			echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/wargus"
+
+			cd /usr/share/games/stratagus/wargus
+			/usr/share/games/stratagus/wargus/build.sh -p ${CDPATH} -b /usr/games -o /usr/share/games/stratagus/wargus -s -c ${EXTRACTVIDEO} ${EXTRACTMUSIC}
+			return $?
+
+		else
+
+			db_stop || true
+			echo "${RET} doesn't exist - can't extract Warcraft II data" >&2
+			return 1
+
+		fi
+
+	fi
+
+	db_stop || true
+	return 0
+
+}
 
 case "$1" in
-  configure)
-      db_get shared/wargusextractdata || true
-      if [ "$RET" = "true" ]; then
-        db_get shared/warguscdpath || true
-        CDPATH=${RET}
-        EXTRACTVIDEO=
-        EXTRACTMUSIC=
-        if [ -d "${CDPATH}" ]; then
-          db_get shared/wargusextractvideo || true
-          if [ ${RET} = "true" ]; then
-            EXTRACTVIDEO="-v"
-          fi
-          db_get shared/wargusextractmusic || true
-          if [ ${RET} = "true" ]; then
-            EXTRACTMUSIC="-m"
-          fi
-          echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/wargus"
-          cd /usr/share/games/stratagus/wargus
-          /usr/share/games/stratagus/wargus/build.sh -p ${CDPATH} -b /usr/games -o /usr/share/games/stratagus/wargus -s -c ${EXTRACTVIDEO} ${EXTRACTMUSIC}
-        else
-          echo "${RET} doesn't exist - can't extract WarCraft II data" >&2
-          exit 1
-        fi
-      fi
-  ;;
-  *)
-    echo "postinst called with unknown argument \`$1'" >&2
-    exit 1
-  ;;
+	configure)
+		extract
+		exit $?
+		;;
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+		;;
 esac
-
-db_stop || true
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
